# Generated by Django 2.1.7 on 2019-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.IntegerField()),
                ('presumptive_tb_target', models.IntegerField()),
                ('presumptive_tb_exam_rate', models.IntegerField()),
            ],
        ),
    ]
