# Generated by Django 2.2.4 on 2019-08-22 05:15

import TB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='township',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=TB.models.current_year)),
                ('total_population', models.IntegerField(default=0)),
                ('target_for_presumptive_tb', models.IntegerField(default=0)),
                ('presumptive_tb_examinationn_rate', models.IntegerField(default=0)),
                ('cnr_bact_confirmed', models.IntegerField(default=0)),
                ('cnr_all_cases', models.IntegerField(default=0)),
                ('treatment_success_rate', models.IntegerField(default=0)),
                ('death_rate', models.IntegerField(default=0)),
                ('new_ss_p_cases', models.IntegerField(default=0)),
                ('relapse_cases', models.IntegerField(default=0)),
                ('smear_positive_unknown_previous_treatment', models.IntegerField(default=0)),
                ('total_no_of_clinically_diagnosed_cased', models.IntegerField(default=0)),
                ('ep_cases', models.IntegerField(default=0)),
                ('hiv_test_among_all_register_tb_cases', models.IntegerField(default=0)),
                ('hiv_positive_case', models.IntegerField(default=0)),
                ('township', models.ForeignKey(on_delete='CASCADE', to='TB.township')),
            ],
        ),
    ]
