# Generated by Django 2.2.4 on 2019-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb',
            name='death_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tb',
            name='treatment_success_rate',
            field=models.FloatField(default=0),
        ),
    ]
