# Generated by Django 2.2.4 on 2019-08-24 19:04
from __future__ import unicode_literals
from django.db import migrations
from django.db import migrations, models

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Township = apps.get_model("TB", "township")
    for township in Township.objects.all():
        township.name = "%s %s" % (township.name)
        township.save()

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('TB', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
