# Generated by Django 2.2.4 on 2019-08-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TB', '0002_auto_20190825_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb',
            name='death_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tb',
            name='treatment_success_rate',
            field=models.IntegerField(default=0),
        ),
    ]
